name: An Example Workflow

run-name: Demo for using matrix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  demo-matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        version: [ 10, 12, 14, 16 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup NodeJs Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Check Version
        run: node --version
