name: An Example Workflow

run-name: Demo Workflow Job

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  demo-actions-chekout:
    runs-on: ubuntu-latest

    steps:
      - name: Display Working Directory
        run: |
          echo "$(pwd)"
          ls -lart

      - name: checkout
        uses: actions/checkout@v3

      - name: Display working directory
        run: |
          echo "$(pwd)"
          ls -lart
  
  demo-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Script
        env:
          USERNAME: ${{ secrets.MY_USERNAME }}
          PASSWORD: ${{ secrets.MY_PASSWORD }}
        run: |
          python test_secret.py 
  
  demo-node-application:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node-JS Environment
        uses: actions/setup-node@v3

      - name: Check Version
        run: |
          node --version
          npm --version
      - name: Installing Required Libraries
        run: | 
          npm install --save moment
      
      - name: Display Date with Message
        run: |
          node app.js
